pdreker/fritz_exporter

fritz_export_helper.py, fritzexporter/fritzcapabilities.py
This script can be used to call actions without arguments and will pretty
print the results.
Also be more defensive about the reported Services and actions: Instead of erroring out, log a warning
=> fix-cable-boxes

.github/workflows/build-and-push-develop.yaml, .gitignore, README.md, fritz_exporter.py
This PR implements the ability to use either a single environment variable to monitor multiple devices or use multiple environment variables for easy use in a kubernetes deployment. This way you can store the password in a kubernetes secret. You lose the ability to monitor more than one device but can spawn multiple deployments for that purpose. I added a section to the Readme how to utilize this.
=> Allow both single and multiple environment variables for Kubernetes deployment

.github/workflows/build-and-push-develop.yaml, .gitignore, README.md, fritz_exporter.py
This release ads the ability to specify configuration in separate Env Vars, to make it easier to put the passwords into a kubernetes secret.
If using this you are currently only able to monitor a single device, but if you are running k8s you can simply deploy multiple exporters to monitor multiple devices.
Thanks to @transacid for the PR.
=> Make nvironment configuration more kubernetes friendly

README.md, fritz_exporter.py
Kubernetes only allows strings in env variables. Explicitly casting server port to and int doesn't hurt when it's already an int but let's you change the port in kubernetes.
also fixed a c&p fail with the names of the env variables in the Readme
=> explicitly cast server port to an int

README.md, fritzexporter/fritzcapabilities.py
This adds new metrics for the current byterate on the WAN Interface., where available (fritz_wan_byterate).
Also documents, that the guest WiFi packet counter will always be "0", as the Fritz API always returns 0 for these counters.
=> New metrics

Pipfile.lock, README.md, fritzexporter/fritzcapabilities.py
Some boxes seem to report a capabilitiy, but when actually calling the action respond with `820 Internal Error`. The capability scanner will now also detect this and disable the metrics for affected boxes.
=> [1.0.6] Also catch "FritzInternalError" when scanning capabilities

README.md
Unfortunately I wasted two hours of my time since I did not notice that the Fritz!Box does not allow passwords longer than 32 characters. This pr adds a note about this unexpected behavior of the router to the README.md so that further users of this exporter will not run into the problem.
Just to clarify: I believe that the exporter behaves exactly as it should 👍 . However, I would like to add this note for documentation purposes so that other users will waste as much time as I did.
Thanks for creating the exporter 💪 .
=> Add note about password length to README.md

docs/RUNNING.md
Btw: Totally missed the RUNNING.md the first 15 minutes, given there's also no link in the README. Might be worth to add a link there on top somewhere.
Thanks for the work on the exporter!
=> docs: Fix broken link

.github/workflows/build-and-push-release.yaml, docs/docker-images.rst, docs/quickstart.rst, docs/running.rst, helm/fritz-exporter/Chart.yaml
No functional or code changes.
* Enable multiple docker tags for releaes (latest, 2, 2.1, 2.1.3, ...
* Automatically bump appVersion in Helm Chart.yaml
=> Move to Multi-Tag docker builds

.github/workflows/build-trunk.yaml, .github/workflows/build_release.yaml, .github/workflows/run-tests.yaml, fritzexporter/fritzcapabilities.py
Fixes #115
Due a wrong indentation the the metrics for host_info were repeatedly delivered in every query causing a quadratic increase in output size over the number of hosts reported by the Fritz device.
This does not improve performance for host_info metrics, but massively reduces the amount of data delivered by the exporter.
=> fix: a lot duplicate metrics when FRITZ_HOST_INFO is enabled

fritzexporter/__main__.py
Fixes #116
Refactoring of Config logic introduced a logic error, where the exporter would *always* use the default log_level, if none was specified in the command line arguments.
=> fix: exporter does not honor log_level from config file.

.github/workflows/build-trunk.yaml
Do not automatically build a pre-release image from trunk: this eats quite some time and building locally for development is trvial. Also avoids polluting the changelogs with repeated merges to trunk.
=> build: do not autobuild trunk

docs/index.rst
This small change adds a dashboard addtionally facilitating the host info metrics.
[Issue #126](https://github.com/pdreker/fritz_exporter/issues/126)
=> docs: add link to dashboard also displaying host info metrics

fritzexporter/data_donation.py
Seems like this field was not caught, when implementing the initial sanitation filter.
=> fix: sanitize (WANIPConnection1, GetInfo, NewExternalIPAddress)

helm/fritz-exporter/templates/secret.yaml, helm/fritz-exporter/templates/servicemonitor.yaml, helm/fritz-exporter/values.yaml
Hey, thanks for this tool and the grafana dashboard.
I deployed the exporter with the helm chart in this repository, but had some problems.
* The scraping interval is an integer and not a string.
* The selectorLabels on the ServiceMonitor can be wrong. The variable should be used, like in the other manifests.
* If the `config` value is not written as a string it can't be converted to base64. But the map can be converted to a yaml string.
=> Fixes for the helm chart

.vscode/settings.json, fritzexporter/fritzcapabilities.py, pyproject.toml
When checking for capabilities fritzconnection may return FritzArgumentError which needs to be caught.
Fixes #203
=> fix: catch FritzArgumentError in capability scan

docs/index.rst
Fritz!OS currently does not report the state of window sensors or the battery state of any device via the TR-064 API.
=> docs(homeauto): explicitly mention missing metrics

pyproject.toml
pyproject.toml specified a script, which interfered with netbsd (and probably others) packaging, as it violates some best practices for building packages/wheels.
The exporter never actually used a script to run, so just remove those two lines, which fixes the problem.
=> build: remove poetry.scripts from pyproject.toml

fritzexporter/data_donation.py, fritzexporter/fritz_aha.py, fritzexporter/fritzcapabilities.py, fritzexporter/fritzdevice.py, poetry.lock, pyproject.toml, tests/fc_services_mock.py, tests/test_fritzdevice.py
This will start reading various Homeautomation metrics via the AHA homeautomation HTTP API from the FritzBox. Currently this only reads BatteryState (Level in %) and BatteryLow (1 = change battery, 0 = OK)
=> feat: add Homeautomation metrics via HTTP

fritzexporter/fritz_aha.py
As previously mentioned here: 
https://github.com/pdreker/fritz_exporter/issues/245#issuecomment-1875912021
My watchtower instance automatically updated my container to the 2.4 release and it started crashing immediately. You mentioned in your comment [here](https://github.com/pdreker/fritz_exporter/issues/245#issuecomment-1890384275) that you would consider just handling the parse error. This is what this patch should do.
Unfortunately, I'm not really able to test because I just can't get poetry installed on my system and I'm still struggling to get a newer python to work since the 3.6 release I have currently won't let me run the code directly.
=> Add handling for xml error when no battery stats are reported by the device

helm/fritz-exporter/Chart.yaml
Hey @pdreker, thank you for `fritz_exporter`! Really great project.
I came across it and used the Helm chart to deploy it, works like a charm. Only modification I had to make was to bump the appVersion to 2.5.0 so it would use the latest version of the exporter (2.2.0 is pretty old at this point, after all).
Helm charts also need a version bump usually, so I took the freedom to bump it from 0.1.0 to 0.2.0 since it has been sitting at that version for a bit too long maybe.
Hope this PR is helpful you, I saw that the Helm chart was considered "a hot mess" at some point, but it seems to be quite solid. If this isn't desired, feel free to close the PR!
=> chore: bump Helm chart to 0.2.0, app version to 2.5.0
